accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name="signup"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
    path('admin/', views.admin_view, name="admin"),
]

anthemology/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from songs import views as song_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('songs/', include('songs.urls')),
    path('', views.home, name="home"),
    path('about/', views.about, name="about"),
    path('song-search/', views.song_search, name="song_search"),
]

songs/urls.py
from django.urls import path
from . import views

app_name = 'songs'

urlpatterns = [
    path('', views.song_list, name="song_list"),
    path('<slug:slug>/', views.song_detail, name="detail"),
    path('my-songs', views.user_songs, name="user_songs"),
    path('add-song', views.add_song, name="add"),
    path('edit-song/<slug:slug>', views.edit_song, name="edit"),
    path('delete-song/<slug:slug>', views.delete_song, name="delete"),
]

accounts/models.py
from django.db import models

# Create your models here.

songs/models.py
from django.db import models
from django.contrib.auth.models import User


class Song(models.Model):
    slug = models.SlugField(unique=True)
    title = models.CharField(unique=True, max_length=100)
    artist = models.CharField(max_length=100)
    album = models.CharField(max_length=100)
    lyrics = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, default=None, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = self.slug
        self.title = self.title.title()
        self.artist = self.artist.title()
        self.album = self.album.title()
        self.lyrics = self.lyrics.title()
        self.date = self.date
        self.author = self.author
        super(Song, self).save(*args, **kwargs)

songs/forms.py
from django import forms
from . import models


class SongForm(forms.ModelForm):
    class Meta:
        model = models.Song
        fields = ['title', 'artist', 'album', 'lyrics']

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, logout
from django.contrib import messages
from songs.models import Song


def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            # log the user in
            login(request, user)
            messages.success(request, "Sign up successful!")
            return redirect('songs:user_songs')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form': form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            # log the user in
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                if request.user.is_superuser:
                    messages.success(request, "Login successful!")
                    return redirect('accounts:admin')
                else:
                    messages.success(request, "Login successful!")
                    return redirect('songs:user_songs')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form': form})


def logout_view(request):
    if request.method == 'POST':
        logout(request)
        messages.success(request, "Logout successful!")
        return redirect('songs:song_list')


@login_required(login_url="/accounts/login/")
def admin_view(request):
    songs = Song.objects.all().order_by('title')
    return render(request, 'accounts/admin.html', {'songs': songs})

anthemology/views.py
from django.shortcuts import render
from django.db.models import Q
from songs.models import Song


def home(request):
    return render(request, 'home.html')


def about(request):
    return render(request, 'about.html')


# code taken from Codemy and adapted - see README
def song_search(request):
    if request.method == 'POST':
        searched = request.POST['searched']
        songs = Song.objects.filter(
            Q(title__icontains=searched) |
            Q(artist__icontains=searched) |
            Q(album__icontains=searched)).order_by('title')
        return render(
            request, 'song_search.html', {
                'searched': searched,
                'songs': songs
                }
            )
    else:
        return render(request, 'song_search.html')

songs/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Song
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.template.defaultfilters import slugify
from . import forms


def song_list(request):
    titles = Song.objects.all().order_by('title')
    artists = Song.objects.all().order_by('artist')
    albums = Song.objects.all().order_by('album')
    return render(request, 'songs/song_list.html', {
        'titles': titles,
        'artists': artists,
        'albums': albums})


def song_detail(request, slug):
    song = Song.objects.get(slug=slug)
    return render(request, 'songs/song_detail.html', {'song': song})


def user_songs(request):
    user_songs = Song.objects.all().filter(
        author=request.user).order_by('title')
    return render(request, 'songs/user_songs.html', {'user_songs': user_songs})


@login_required(login_url="/accounts/login/")
def add_song(request):
    if request.method == 'POST':
        form = forms.SongForm(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.slug = slugify(instance.title)
            if instance.slug == instance.title:
                messages.error(request, "Title already exists!")
            else:
                messages.success(request, "Your song has been added!")
                instance.save()
            return redirect('songs:user_songs')
    else:
        form = forms.SongForm()
    return render(request, 'songs/add_song.html', {'form': form})


@login_required(login_url="/accounts/login/")
def edit_song(request, slug):
    song = Song.objects.get(slug=slug)
    form = forms.SongForm(request.POST, instance=song)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.slug = slugify(instance.title)
        instance.save()
        if request.user.is_superuser:
            messages.success(request, "The song has been edited!")
            return redirect('accounts:admin')
        else:
            messages.success(request, "Your song has been edited!")
            return redirect('songs:user_songs')
    else:
        form = forms.SongForm(instance=song)
        return render(request, 'songs/edit_song.html', {
            'song': song,
            'form': form})


@login_required(login_url="/accounts/login/")
def delete_song(request, slug):
    song = Song.objects.get(slug=slug)
    if request.method == 'POST':
        song.delete()
        if request.user.is_superuser:
            messages.success(request, "The song has been deleted!")
            return redirect('accounts:admin')
        else:
            messages.success(request, "Your song has been deleted!")
            return redirect('songs:user_songs')
    else:
        return render(request, 'songs/delete_song.html', {'song': song})

accounts/templates/accounts/admin.html
{% extends 'base_layout.html' %}

{% load static %}

{% block content %}
    <section class="hero-page-wrapper">
        <div class="hero-image-container">
            <div class="hero-image-content">
                <div class="page-header">
                    <h2 class="page-header-title">Admin View</h2>
                </div>
                <div class="page-content">
                    <p>
                        <ul>
                            <li>Welcome <span class="text-highlight">{{ user }}!</span></li>
                            <li>Here you'll find every single song that has been added to the database.</li>
                            <li>You can view, edit, and delete them as wished.</li>
                        </ul>
                    </p>
                    <p>
                        <div class="user-songs">
                            {% for song in songs %}
                                <div class="song">
                                    <div class="song-card">
                                        <a href="{% url 'songs:detail' slug=song.slug %}">
                                            <h4>{{ song.title }}</h4>
                                            <p>Artist: {{ song.artist }}</p>
                                            <p>Album: {{ song.album }}</p>
                                            <p>Added By: {{ song.author.username }}</p>
                                        </a>
                                        <div class="song-buttons">
                                            <a href="{% url 'songs:edit' slug=song.slug %}">
                                                <button>Edit Song</button>
                                            </a>
                                            <a href="{% url 'songs:delete' slug=song.slug %}">
                                                <button>Delete Song</button>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </p>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% load static %}

{% block content %}
    <section class="hero-page-wrapper">
        <div class="hero-image-container">
            <div class="hero-image-content">
                <div class="page-header">
                    <h2 class="page-header-title">Login</h2>
                </div>
                <div class="page-content">
                    <form class="site-form" action="{% url 'accounts:login' %}" method="post">
                        {% csrf_token %}
                        {{ form }}
                        {% if request.GET.next %}
                            <input type="hidden" name="next" value="{{ request.GET.next }}">
                        {% endif %}
                        <input class="button" type="submit" value="Login">
                    </form>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% load static %}

{% block content %}
    <section class="hero-page-wrapper">
        <div class="hero-image-container">
            <div class="hero-image-content">
                <div class="page-header">
                    <h2 class="page-header-title">Signup</h2>
                </div>
                <div class="page-content">
                    <form class="site-form" action="{% url 'accounts:signup' %}" method="post">
                        {% csrf_token %}
                        {{ form }}
                        <input class="button" type="submit" value="Signup">
                    </form>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

songs/templates/songs/add_song.html
{% extends 'base_layout.html' %}

{% load static %}

{% block content %}
    <section class="hero-page-wrapper">
        <div class="hero-image-container">
            <div class="hero-image-content">
                <div class="page-header">
                    <h2 class="page-header-title">Add A Song</h2>
                </div>
                <div class="page-content">
                    <form class="site-form song-form" action="{% url 'songs:add' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form }}
                        <input class="button" type="submit" value="Add">
                    </form>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

songs/templates/songs/delete_song.html
{% extends 'base_layout.html' %}

{% load static %}

{% block content %}
    <section class="hero-page-wrapper">
        <div class="hero-image-container">
            <div class="hero-image-content">
                <div class="page-header">
                    <h2 class="page-header-title">Delete Song?</h2>
                </div>
                <div class="page-content">
                    <ul class="song-info">
                        <li>Title: {{ song.title }}</li>
                        <li>Artist: {{ song.artist }}</li>
                        <li>Album: {{ song.album }}</li>
                    </ul>
                    <form class="site-form" action="{% url 'songs:delete' slug=song.slug %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input class="button" type="submit" value="Delete">
                    </form>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

songs/templates/songs/edit_song.html
{% extends 'base_layout.html' %}

{% load static %}

{% block content %}
    <section class="hero-page-wrapper">
        <div class="hero-image-container">
            <div class="hero-image-content">
                <div class="page-header">
                    <h2 class="page-header-title">Edit Song</h2>
                </div>
                <div class="page-content">
                    <form class="site-form song-form" action="{% url 'songs:edit' slug=song.slug %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form }}
                        <input class="button" type="submit" value="Update">
                    </form>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

songs/templates/songs/song_detail.html
{% extends 'base_layout.html' %}

{% load static %}

{% block content %}
    <section class="wrapper">
        <div class="page-header">
            <h2 class="page-header-title">Song Lyrics</h2>
        </div>
        <div class="page-content">
            <div class="song-detail">
                <div class="jukebox">
                    <div class="jukebox-item">
                        <div class="jukebox-image">
                            <img src="{% static 'images/vinyl_graphic.png' %}" alt="default artwork image of vinyl graphic">
                            <img src="{% static 'images/vinyl_graphic.png' %}" alt="default artwork image of vinyl graphic">
                            <img src="{% static 'images/vinyl_graphic.png' %}" alt="default artwork image of vinyl graphic">
                            <img src="{% static 'images/vinyl_graphic.png' %}" alt="default artwork image of vinyl graphic">
                        </div>
                    </div>
                    <div class="jukebox-item song-info">
                        <h3 class="text-highlight">{{ song.title }}</h3>
                        <p>Artist: {{ song.artist }}</p>
                        <p>Album: {{ song.album }}</p>
                        <p>Added By: {{ song.author }}</p>
                        <p>Added On: {{ song.date }}</p>
                    </div>
                </div>
                <div class="homepage-image-container">
                    <div class="hero-image-content">
                        <div class="song-lyrics">
                            <p>{{ song.lyrics }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

songs/templates/songs/song_list.html
{% extends 'base_layout.html' %}

{% load static %}

{% block content %}
    <section class="hero-page-wrapper">
        <div class="hero-image-container">
            <div class="hero-image-content">
                <div class="page-header-with-button">
                    <h2 class="page-header-title-with-button">Songs</h2>
                    <div class="page-header-item">
                        <a class="button" href="{% url 'songs:add' %}">Add Song</a>
                    </div>
                </div>
                <div class="page-content">
                    <div class="song-list">
                        <!-- By Title -->
                        <div class="song-list-item">
                            <h3 class="song-list-title">
                                <span class="text-highlight">By Title</span>
                            </h3>
                            <div class="song-list-song">
                            {% for title in titles %}
                                <a href="{% url 'songs:detail' slug=title.slug %}">
                                    {{ title.title }}
                                </a>
                            {% endfor %}
                            </div>
                        </div>
                        <!-- By Artist -->
                        <div class="song-list-item">
                            <h3 class="song-list-title">
                                <span class="text-highlight">By Artist</span>
                            </h3>
                            <div class="song-list-song">
                            {% for artist in artists %}
                                <a href="{% url 'songs:detail' slug=artist.slug %}">
                                    {{ artist.artist }}
                                </a>
                            {% endfor %}
                            </div>
                        </div>
                        <!-- By Album -->
                        <div class="song-list-item">
                            <h3 class="song-list-title">
                                <span class="text-highlight">By Album</span>
                            </h3>
                            <div class="song-list-song">
                            {% for album in albums %}
                                <a href="{% url 'songs:detail' slug=album.slug %}">
                                    {{ album.album }}
                                </a>
                            {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

songs/templates/songs/user_songs.html
{% extends 'base_layout.html' %}

{% load static %}

{% block content %}
    <section class="hero-page-wrapper">
        <div class="hero-image-container">
            <div class="hero-image-content">
                <div class="page-header-with-button">
                    <h2 class="page-header-title-with-button">My Songs</h2>
                    <div class="page-header-item">
                        <a class="button" href="{% url 'songs:add' %}">Add Song</a>
                    </div>
                </div>
                <div class="page-content">
                    <p>
                        <ul>
                            <li>Welcome <span class="text-highlight">{{ user }}!</span></li>
                            <li>Here you'll find all the songs you've added, as well as the possibility of editing and deleting them as wished.</li>
                            <li>If you haven't added any songs yet, feel free to create one via the 'Add Song' button above.</li>
                        </ul>
                    </p>
                    <p>
                        {% if user_songs %}
                        <div class="user-songs">
                            {% for user_song in user_songs %}
                                <div class="song">
                                    <div class="song-card">
                                        <a href="{% url 'songs:detail' slug=user_song.slug %}">
                                            <h4>{{ user_song.title }}</h4>
                                            <p>Artist: {{ user_song.artist }}</p>
                                            <p>Album: {{ user_song.album }}</p>
                                            <p>Added By: {{ user_song.author.username }}</p>
                                        </a>
                                        <div class="song-buttons">
                                            <a href="{% url 'songs:edit' slug=user_song.slug %}">
                                                <button>Edit Song</button>
                                            </a>
                                            <a href="{% url 'songs:delete' slug=user_song.slug %}">
                                                <button>Delete Song</button>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    {% else %}
                        <div class="section-alert">
                            <p>You haven't added any songs yet.</p>
                        </div>
                    {% endif %}
                    </p>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/about.html
{% extends 'base_layout.html' %}

{% load static %}

{% block content %}
    <section class="hero-page-wrapper">
        <div class="hero-image-container">
            <div class="hero-image-content">
                <div class="page-header">
                    <h2 class="page-header-title">About Anthemology</h2>
                </div>
                <div class="page-content">
                    <ul>
                        <li>Anthemology was created for all music lovers out there!</li>
                        <li>Want to sing along to your favourite tune?</li>
                        <li>Take a look at our expansive catalogue of songs, either via the search bar, or the Songs page.</li>
                        <li>Can't find the song you're looking for?</li>
                        <li>Sign up and add it to the collection!</li>
                        <li>You can find your songs on the My Songs page.</li>
                        <li>Here you can edit, or delete your contributions at any time.</li>
                    </ul>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/base_layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <!-- meta elements -->
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description"
        content="Anthemology was created for all music lovers out there! Want to sing along to your favourite tune? Take a look at our expansive catalogue of songs, either via the search bar, or the Songs page. Can't find the song you're looking for? Sign up and add it to the collection! You can find your songs on the My Songs page. Here you can edit, or delete your contributions at any time.">
    <meta name="keywords"
        content="Anthemology, music, songs, lyrics, singing">
    <meta name="author" content="Alexa Hendry">

    <!-- site title and favicon -->
    <title>Anthemology</title>
    <link rel="icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}">

    <!-- css -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

    <!-- font awesome kit -->
    <script src="https://kit.fontawesome.com/5366bdfdf4.js" crossorigin="anonymous"></script>
</head>

<body>
    <!-- header -->
    <header>
        <!-- site logo -->
        <div class="header-item">
            <ul>
                <li class="header-logo">
                    <i class="fa-solid fa-microphone-lines" aria-hidden="true"></i>
                </li>
                <li class="header-logo">
                    <h1>
                        <a href="{% url 'home' %}" aria-label="Link to the site's homepage">Anthemology</a>
                    </h1>
                </li>
            </ul>
        </div>
        <!-- search bar -->
        <div class="header-item">
            <ul>
                <li>
                    <!-- code taken from Codemy and adapted - see README -->
                    <form class="nav-search-bar" method="post" action="{% url 'song_search' %}">
                        {% csrf_token %}
                        <input type="search" placeholder="Search Songs" name="searched" aria-label="Song Search Bar" required>
                        <button type="submit">Search</button>
                    </form>
                </li>
            </ul>
        </div>
        <!-- navigation links -->
        <nav class="header-item">
            <ul>
                <!-- link to homepage -->
                <li>
                    <a href="{% url 'home' %}">Home</a>
                </li>
                <!-- link to song list -->
                <li>
                    <a href="{% url 'songs:song_list' %}">Songs</a>
                </li>
                <!-- link to about page -->
                <li>
                    <a href="{% url 'about' %}">About</a>
                </li>
                {% if user.is_authenticated %}
                    {% if user.is_superuser %}
                    <!-- link to admin view -->
                    <li>
                        <a href="{% url 'accounts:admin' %}">Admin</a>
                    </li>
                    {% else %}
                    <!-- link to user's songs -->
                    <li>
                        <a href="{% url 'songs:user_songs' %}">My Songs</a>
                    </li>
                    {% endif %}
                <!-- link to log out -->
                <li>
                    <form class="logout" action="{% url 'accounts:logout' %}" method="post">
                        {% csrf_token %}
                        <button type="submit">Logout</button>
                    </form>
                </li>
                {% else %}
                <!-- link to sign up -->
                <li>
                    <a href="{% url 'accounts:signup' %}">Signup</a>
                </li>
                <!-- link to log in -->
                <li class="login">
                    <a class="login-button" href="{% url 'accounts:login' %}">Login</a>
                </li>
                {% endif %}
            </ul>
        </nav>
    </header>

    <main>
        {% block content %}
        {% endblock %}
        <div class="message-wrapper">
            {% if messages %}
            <ul class="alert">
                {% for message in messages %}
                <!-- close button code taken from W3Schools - more info in README -->
                <span class="alert-close-button" onclick="this.parentElement.style.display='none';">&times;</span>
                <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>
                    {{ message }}
                </li>
                {% endfor %}
            </ul>
            {% endif %}
        </div>
    </main>

    <!-- footer -->
    <footer>
        <!-- site name -->
        <div class="footer-item" id="footer-logo">
            <p>
                Anthemology<sup id="footer-copyright">&copy;</sup>
            </p>
        </div>
        <!-- about site -->
        <div class="footer-item">
            <p id="footer-text">
                This website was created by Alexa Hendry as a portfolio project and has no commercial purpose.
            </p>
        </div>
        <!-- site creator social media links -->
        <div class="footer-item footer-socials">
            <ul>
                <li>
                    <a href="https://github.com/AlexaH88" target="_blank"
                        aria-label="Link to Alexa Hendry's GitHub profile (opens in a new tab)"><i
                            class="fa-brands fa-github-alt"></i></a>
                    <a href="https://www.linkedin.com/in/alexa-hendry/" target="_blank"
                        aria-label="Link to Alexa Hendry's LinkedIn profile (opens in a new tab)"><i
                            class="fa-brands fa-linkedin"></i></a>
                </li>
            </ul>
        </div>
    </footer>

</body>

</html>

templates/home.html
{% extends 'base_layout.html' %}

{% load static %}

{% block content %}
    <div class="homepage-wrapper">
        <div class="homepage-image-container">
            <div class="homepage-image-content">
                <form class="homepage-search-bar" method="post" action="{% url 'song_search' %}">
                    {% csrf_token %}
                    <input type="search" placeholder="Search Songs" name="searched" aria-label="Song Search Bar" required>
                    <button type="submit">Search</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/song_search.html
{% extends 'base_layout.html' %}

{% load static %}

{% block content %}
    <section class="hero-page-wrapper">
        <div class="hero-image-container">
            <div class="hero-image-content">
                <div class="page-header">
                    <h2 class="page-header-title">Your Search Results</h2>
                </div>
                <div class="page-content">
                    {% if searched %}
                        <div class="songs">
                            {% for song in songs %}
                                <div class="song">
                                    <a class="song-card" href="{% url 'songs:detail' slug=song.slug %}">
                                        <h3>{{ song.title }}</h3>
                                        <p>Artist: {{ song.artist }}</p>
                                        <p>Album: {{ song.album }}</p>
                                    </a>
                                </div>
                            {% endfor %}
                        </div>
                    {% else %}
                    <div class="section-alert">
                        <p>The song you searched couldn't be found. Please try again.</p>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </section>
{% endblock %}